services:
  geth:
    image: ghcr.io/ethscriptions-protocol/ethscriptions-geth:ethscriptions
    environment:
      JWT_SECRET: ${JWT_SECRET}
      GENESIS_FILE: ${GENESIS_FILE}
      GENESIS_TIMESTAMP: ${GENESIS_TIMESTAMP:-}
      GENESIS_MIX_HASH: ${GENESIS_MIX_HASH:-}
      RPC_GAS_CAP: ${RPC_GAS_CAP:-500000000}
      CACHE_SIZE: ${GETH_CACHE_SIZE:-25000}
      ENABLE_PREIMAGES: ${ENABLE_PREIMAGES:-true}
      GC_MODE: ${GC_MODE:-full}
      STATE_HISTORY: ${STATE_HISTORY:-100000}
      TX_HISTORY: ${TX_HISTORY:-100000}
      CACHE_GC: ${CACHE_GC:-25}
      CACHE_TRIE: ${CACHE_TRIE:-15}
    volumes:
      - geth-data:/root/ethereum
    ports:
      - "${GETH_EXTERNAL_PORT:-8545}:8545"
    healthcheck:
      test: ["CMD-SHELL", "geth attach --exec 'eth.blockNumber' http://localhost:8545"]
      interval: 30s
      timeout: 3s
      retries: 20
      start_period: 10s

  node:
    image: ghcr.io/ethscriptions-protocol/ethscriptions-node:evm-backend-demo
    environment:
      JWT_SECRET: ${JWT_SECRET}
      L1_NETWORK: ${L1_NETWORK}
      GETH_RPC_URL: ipc:///geth-data/geth.ipc
      NON_AUTH_GETH_RPC_URL: ipc:///geth-data/geth.ipc
      L1_RPC_URL: ${L1_RPC_URL}
      L1_GENESIS_BLOCK: ${L1_GENESIS_BLOCK}
      L1_PREFETCH_FORWARD: ${L1_PREFETCH_FORWARD:-200}
      L1_PREFETCH_THREADS: ${L1_PREFETCH_THREADS:-10}
      VALIDATION_ENABLED: ${VALIDATION_ENABLED:-false}
      JOB_CONCURRENCY: ${JOB_CONCURRENCY:-6}
      JOB_THREADS: ${JOB_THREADS:-3}
      PROFILE_IMPORT: ${PROFILE_IMPORT:-true}
      ETHSCRIPTIONS_API_BASE_URL: ${ETHSCRIPTIONS_API_BASE_URL:-}
      # Transient validation error handling configuration
      VALIDATION_TRANSIENT_RETRIES: ${VALIDATION_TRANSIENT_RETRIES:-1000}
      VALIDATION_RETRY_WAIT_SECONDS: ${VALIDATION_RETRY_WAIT_SECONDS:-5}
      ETHSCRIPTIONS_API_RETRIES: ${ETHSCRIPTIONS_API_RETRIES:-7}
      # Validation lag control
      VALIDATION_LAG_HARD_LIMIT: ${VALIDATION_LAG_HARD_LIMIT:-30}
      ETHSCRIPTIONS_API_KEY: ${ETHSCRIPTIONS_API_KEY:-}
      RAILS_MAX_THREADS: ${RAILS_MAX_THREADS:-}
      DEBUG_KEEP_ALIVE: ${DEBUG_KEEP_ALIVE:-0}
    volumes:
      - node-storage:/rails/storage
      - geth-data:/geth-data
    depends_on:
      geth:
        condition: service_healthy

volumes:
  geth-data:
    name: ${COMPOSE_PROJECT_NAME:-ethscriptions-evm}_geth-data
  node-storage:
    name: ${COMPOSE_PROJECT_NAME:-ethscriptions-evm}_node-storage
